
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: databaseuser
  password: databaseuser
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twygo_courses_development

test:
  <<: *default
  database: twygo_courses_test

production:
  <<: *default
  database: twygo_courses_production
  username: twygo_courses
  password: twygo_courses
  host: <%= ENV['DATABASE_URL'] %>
